from flask import Flask,send_from_directory
from flask_socketio import SocketIO
from socketio import ASGIApp  # ASGI Adapter for Flask-SocketIO

import os
import asyncio
from llms_module import App

app = Flask(__name__)
app.config["SECRET_KEY"] = "your-secret-key"
socketio = SocketIO(app, cors_allowed_origins="*")  # Use async mode for Flask-SocketIO

audio_file = None
objectApp = App()
saved_prompt=[]
wav_file_path = "received_audio/recording.wav"

@socketio.on("start")
def handle_start():
    global audio_file
    os.makedirs(os.path.dirname(wav_file_path), exist_ok=True)
    audio_file = open(wav_file_path, "wb")
    print("Started recording and file opened.")

@socketio.on("audio_chunk")
def handle_audio_chunk(audio_data):
    print("receiving")

    global audio_file
    if audio_file:
        print(f"Received chunk of size: {len(audio_data)} bytes")
        audio_file.write(audio_data)


@socketio.on("stop")
def on_stop():
    print("flask Stopping recording...")
    global audio_file
    try:

        if audio_file:
            audio_file.close()
            print(f"Recording stopped and saved at {wav_file_path}")
            
            # Await the async method call
            objectApp.groq_whisper(wav_file_path, add_to_history=True)
            audio_urls = [f'http://127.0.0.1:5000/audios/{file.split("/")[-1]}' for file in objectApp.outputPaths]
            interviewers=objectApp.LLM_reply
            
            # Access output paths generated by App
            print("Generated audio paths:", audio_urls)
            socketio.emit("audio_urls", {"files": audio_urls,"interviewers":interviewers})
    except Exception as e:
        print(f"Error during transcription: {e}")
    finally:
        audio_file = None  # Reset the file reference

@app.route('/audios/<path:filename>')
def serve_audio(filename):
    return send_from_directory('AUDIOS', filename)

@socketio.on("connect")
def handle_connect():
    print("Client connected")

@socketio.on("message")
def handle_message():
    print("IN MESSAGE")

@socketio.on("disconnect")
def handle_disconnect():
    global audio_file
    global objectApp
    global saved_prompt
    saved_prompt.append(objectApp.prompt[0])
    objectApp.clear_prompt()
    if audio_file:
        audio_file.close()
        print("File closed due to client disconnect.")
        audio_file = None
    print("Client disconnected")


@app.route("/report")
def gen_report():
    global saved_prompt
    userhistory=[{"role":"user","content":"This is the user and model communication => "+str(saved_prompt[1:])}]
    report_prompt=[{"role":"system",
                    "content":"You are a helpful assistant that will generate a report based on the given conversation. "},
        {
        "role": "user",
        "content": [
            "I will provide a Json to you, It contains the conversation between Model and user, You have to generate a extreamly detailed report of their mistakes and also score them widely , point there mistakes from the conversation to give examples\nformat \n{ \"Interview Report\": {role,Scenario}\n  \"fluency\": \"7.5\",\n  \"mistakes\": [ explain in detail],\n  \"scores\": { explain in detail\n    \"clarity\": 8,\n    \"confidence\": 7,\n    \"accuracy\": 6\n  },\n  \"visualization_data\": {\n    \"line_chart_fluency\": [\n      { \"response\": 1, \"fluency_score\": 6 },\n      { \"response\": 2, \"fluency_score\": 7 },\n      ...\n    ],\n    \"bar_chart_mistakes\": {\n      \"tenses\": 5,\n      \"word_usage\": 3,\n      \"sentence_structure\": 4\n    },\n    \"pie_chart_communication_clarity\": {\n      \"clarity_score\": 8,\n      \"communication_score\": 7\n    }\n  },\n  \"suggested_improvements\": [\"mprove sentence structure and choice of words.\"],\n  \"benchmark_comparison\": {\n    \"average_fluency\",\n    \"average_clarity\",\n    \"average_accuracy\"\n  },\n  \"summary\": \"The candidate shows strong clarity and communication skills but could improve in sentence structure and word choice to achieve greater accuracy.\"\n}",
        ],
        },
        {
        "role": "assistant",
        "content": [
            "```json\n{\"Interview Report\": {\"role\": \"Model\", \"Scenario\": \"Conversation between Model and user\"}, \"fluency\": \"7.5\", \"mistakes\": [\"The candidate displayed minor grammatical errors in some responses, particularly in tense usage. For example, in response 3, the candidate used the past tense instead of the present tense, leading to a slightly confusing sentence structure.  \", \"There were a few instances where the candidate could have used more precise vocabulary to express their thoughts more effectively. In response 5, for instance, the word 'stuff' could have been replaced with a more specific and descriptive term, improving the overall clarity of the message.\", \"While the candidate generally provided relevant information, some responses lacked sufficient detail and could have been expanded upon to provide a more comprehensive answer. For example, in response 7, the candidate could have offered more specific examples to illustrate their point.\"], \"scores\": {\"clarity\": 8, \"confidence\": 7, \"accuracy\": 6}, \"visualization_data\": {\"line_chart_fluency\": [{\"response\": 1, \"fluency_score\": 6}, {\"response\": 2, \"fluency_score\": 7}, {\"response\": 3, \"fluency_score\": 8}, {\"response\": 4, \"fluency_score\": 7}, {\"response\": 5, \"fluency_score\": 6}, {\"response\": 6, \"fluency_score\": 8}, {\"response\": 7, \"fluency_score\": 7}], \"bar_chart_mistakes\": {\"tenses\": 5, \"word_usage\": 3, \"sentence_structure\": 4}, \"pie_chart_communication_clarity\": {\"clarity_score\": 8, \"communication_score\": 7}}, \"suggested_improvements\": [\"Improve sentence structure and choice of words.\", \"Pay attention to verb tense consistency.\", \"Provide more detailed and specific explanations.\"], \"benchmark_comparison\": {\"average_fluency\": \"7.2\", \"average_clarity\": \"7.8\", \"average_accuracy\": \"6.5\"}, \"summary\": \"The candidate demonstrates strong clarity and communication skills, but could benefit from improving sentence structure, word choice, and providing more detailed responses for increased accuracy.  Overall, they performed well in this conversation, showcasing good understanding and fluency.\"}\n\n```",
        ],
        },
    ]
    report_prompt.append(userhistory)

    objectApp.gorq_LLM(prompt=report_prompt, add_to_history=False)
    data=objectApp.LLM_reply
    print(data)
    return{"message": data}
if __name__ == "__main__":
    socketio.run(app, debug=True)
